### ISSUE TITLE
Relayer Stops After throwing error EOF. 

### ISSUE THREAD

**Issue by Arunhfb** [cosmos/peggy#101]
Relayer stopped automatically after throwing EOF error.Attached screenshot for reference.
![Screenshot from 2019-11-20 18-03-10](https://user-images.githubusercontent.com/52598934/69239407-22946b80-0bc0-11ea-9924-8ac19c408b0d.png)

**Comment by njmurarka** [comment]
I couldn't see the error you have described, but I have had issues with the relayers crashing on me. It happens when I am both locking up tokens on Ethereum for movement to Cosmos, and vice versa. The common thread is it is all in the "ebrelayer" executable. 

I have not found a resolution yet. At the risk of exaggerating, I have found that the relayer is quite "unstable" in both the unlock and lock flows... I will be looking into resolving why the crash occurs, but am still trying to understand Cosmos better first.

**Comment by denalimarsh** [comment]
https://github.com/cosmos/peggy/pull/106 addresses these issues
