### ISSUE TITLE
How to relay a missed transaction?

### ISSUE THREAD

**Issue by okwme** [cosmos/peggy#124]
If the relayer is offline or unable to relay a message, what are the methods for making sure it is carried out afterwards when the relayer is back online?

**Comment by denalimarsh** [comment]
Currently, the relayer must be online in order to relay messages. Future work should include:
- resending failed transactions (with a timeout or attempt limit)
- querying of blocks in range [StartBlockHeight, CurrentBlockHeight] upon relayer initialization and the attempted relay of txs contained within those blocks

**Comment by okwme** [comment]
Both chains contain some ability to query previous transactions etc. Maybe the relayer should be make those kinds of queries automatically to check if a transaction has already been sent and whether is was successful. This could also be useful in the race conditions that are mentioned as an outstanding problem within the relayer code.
