### ISSUE TITLE
Create & Discuss Design Doc for Peggy V3

### ISSUE THREAD

**Issue by okwme** [cosmos/peggy#141]
The `operator` roles have an inordinate amount of power in this system. What are the current proposals for further decentralization and security of Peggy?

 * Using another oralce for validator sets and weights?
 * Including validator sets and weights with every claim to keep them self updated?
 * Threshold signatures of claims that can be collected off chain and verified on chain?

**Comment by cwgoes** [comment]
@okwme What are the actionables here? Is the next step perhaps a separate design document?

**Comment by okwme** [comment]
I think that's a good idea. I'd keep this issue open for the design doc to be posted and discussed as well as alternative ideas / designs.

**Comment by jkbrooks** [comment]
@cwgoes It would be great to get your feedback on the latest cryptoeconomic spec doc I emailed you in relation to this.

The original plan for decentralization of this bridge was to make the "bridge owner" the set of Peggy validators rather than a single entity.  I still think this is the best approach for our architecture

**Comment by fedekunze** [comment]
I'd like to collaborate here too
