### ISSUE TITLE
relayer ropsten network integration not working

### ISSUE THREAD

**Issue by arun1705** [cosmos/peggy#84]
I tried running the ropsten netwrok integration for automatic relaying process but it seems it is not working properly.The relayer is not able to connect to the deployed address showing web socket issue.I have attached screenshot for the reference
![Screenshot from 2019-10-25 11-38-03](https://user-images.githubusercontent.com/41661371/67547336-783e3b00-f71c-11e9-8803-ec7aee10be88.png)

**Comment by denalimarsh** [comment]
Instead of using provider `wss://ropsten.infura.io/`, can you attempt to start the relayer with provider `wss://ropsten.infura.io/ws` as described in section 'Running the relayer service' of the README? 

Here's a screenshot which shows the issue reproduced, and then resolved by using the recommended provider:
<img width="1116" alt="Screen Shot 2019-10-24 at 11 54 58 PM" src="https://user-images.githubusercontent.com/15370712/67550064-793e8080-f6ba-11e9-95d1-47fd28b3a244.png">

Thank you for the screenshots which allowed for a quick diagnosis of this issue. Please let us know if you continue having difficulty with the relayer service.

**Comment by Arunhfb** [comment]
Thank you for your quick response.Its working fine now.But i saw there is some issue with the truffle_config.js it doesnt inject the .env parameters properly.So to make things work i hard coded the parameters i.e. MNEMONIC & INFURA_PROJECT_ID into the js file directly.

And also in the below command it accepts only cosmos_recipient addresses or it can accept any other prefix addresses? 

yarn peggy:lock --network ropsten [HASHED_COSMOS_RECIPIENT_ADDRESS] [TOKEN_CONTRACT_ADDRESS] [WEI_AMOUNT]

**Comment by Arunhfb** [comment]
I tried doing transaction after starting automatic relayer service but facing issues.I have attached screenshot for your reference.
![Screenshot from 2019-10-25 13-35-15](https://user-images.githubusercontent.com/52598934/67554306-bb080f00-f72c-11e9-8c17-589e845ab664.png)

**Comment by denalimarsh** [comment]
I've opened PR https://github.com/cosmos/peggy/pull/85 which addresses both issues. Once it's merged, you'll be able to send the lock transaction with the following process:

1. Migrate the contracts to the ropsten network with `yarn migrate --network ropsten`
2. Send lock transaction to contract with `yarn peggy:lock [HASHED_COSMOS_RECIPIENT_ADDRESS] [TOKEN_CONTRACT_ADDRESS] [WEI_AMOUNT]`
<img width="1135" alt="Screen Shot 2019-10-27 at 3 50 39 PM" src="https://user-images.githubusercontent.com/15370712/67643189-c34d7f00-f8d1-11e9-8420-c6afaac48556.png">

As the production version of the Bridge currently supports only Ethereum -> Cosmos transfers, only hashed Cosmos recipient addresses are valid. For your initial test of the system, I recommend using the `testuser` address from the Bridge blockchain. You can get the testuser's address in plain text with the command `ebcli keys show testuser -a`.
